version: '2'
services:
  confluence_db:
    image: mysql:5.7
    volumes:
      - ./mysql/:/etc/mysql/conf.d/
      - ./db_data:/var/lib/mysql
    restart: always
    #ports:
    #  - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: confluence
      MYSQL_USER: confluence
      MYSQL_PASSWORD: confluence123
  confluence:
    links:
      - confluence_db
    depends_on:
      - confluence_db
    build: .
    ports:
      - "8090:8090"
      - "8091:8091"
